# Generated by Django 3.1.4 on 2021-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210505_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.PNG', upload_to='D:\\Arshita\\blog_project\\media'),
        ),
    ]
